import Recipe from '../models/Recipe';

export default [
    new Recipe(
        0,
        'Fleisch',
        'Grüne Bohnen im Speckmantel',
        [
            {amount:'800', unit: 'g', ingredient:'Bohnen, grüne, frische'},
            {amount:'1', unit: 'Bund' , ingredient: 'Bohnenkraut '},
            {amount:'1', unit: '' , ingredient: 'Knoblauchzehe(n)'},
            {amount:'2', unit: 'TL', ingredient: 'Pfefferkörner'},
            {amount:'1', unit: 'EL', ingredient: 'Öl'},
            {amount:'8', unit: 'Scheibe/n', ingredient: 'Bacon'},
            {amount:'8',unit: 'EL' , ingredient: 'Butter'},
        ],
        [
            'Bohnen waschen und die Spitzen abschneiden.',
            'Bohnenkraut, Knoblauch, zerdrückte Pfefferkörner und Salz mit Öl kurz anrösten. 2 Liter Wasser zugießen, 10 Min. kochen, durchsieben. Diese Brühe aufkochen und die Bohnen in 3 Portionen nacheinander sprudelnd garen. Schnell in kaltem Wasser abkühlen, in einem Tuch abtrocknen.',
            'Zugedeckt im heißen Ofen bei 180 °C - 200 °C Ober-/Unterhitze erhitzen (ca. 5 Minuten), dabei einmal wenden.',
            'Die Bohnen sind eine schöne sommerliche Beilage zu festlichen Gerichten oder ein köstliches Hauptgericht mit ein paar Kartöffelchen.'
        ],
        'Grüne Bohnen im Speckmantel',
        '4',
        '30 min',
        'https://img.chefkoch-cdn.de/rezepte/563451154612271/bilder/1124631/crop-642x428/gruene-bohnen-im-speckmantel.jpg'),
    new Recipe(
        1,
        'Gemüse',
        'Gefüllte Zucchini aus dem Ofen',
        [
            {amount:'2', unit: '', ingredient:'Zucchini (ca. 300 - 340 g)'},
            {amount:'150', unit : 'g', ingredient: 'Frischkäse'},
            {amount:'100', unit : 'g', ingredient: 'Champignons '},
            {amount:'1', unit : 'kleine', ingredient: 'Zwiebel(n)'},
            {amount:'80', unit : 'g', ingredient: 'Cheddarkäse oder Gouda, gerieben (ca. 80 - 100 g)'},
            {amount:'', unit: '', ingredient: 'Salz und Pfeffer'},
        ],
        [
            'Als erstes werden die gewaschenen Zucchini der Länge nach halbiert und mit einem Löffel ausgehöhlt.',
            'Das ausgehöhlte Fruchtfleisch muss anschließend ganz fein gehackt werden. Außerdem kommen noch ganz fein gehackte Champignons, Zwiebeln und Knoblauch in die Füllung, sowie Frischkäse, Salz und Pfeffer. ',
            'Wenn sich alle Zutaten gut vermengt haben, kann die Füllung auch schon in den ausgehöhlten Zucchinihälften verteilt und glatt gestrichen werden. Am besten werden sie anschließend in eine leicht gefettete Auflaufform gelegt, mit geriebenem Cheddar oder Gouda bedeckt und danach im heißen Backofen bei 200 °C Ober-/Unterhitze ca. 20 - 25 Minuten gebacken.',
            'Als Beilage passen übrigens gekochter Reis oder frisches Baguette super gut.'
        ],
        'Gefüllte Zucchini aus dem Ofen',
        '4',
        '20 min',
        'https://img.chefkoch-cdn.de/rezepte/3089761461661487/bilder/1509483/crop-642x428/gefuellte-zucchini-aus-dem-ofen.jpg'),
    new Recipe(
        2,
        'Gemüse',
        'Chili con Carne',
        [
            {amount:'800', unit: "g", ingredient:'Rinderhackfleisch oder halb und halb'},
            {amount:'2', unit: "m.-große", ingredient: 'Zwiebel(n)'},
            {amount:'3', unit: "Zehe/n", ingredient: 'Knoblauch'},
            {amount:'2', unit: "EL", ingredient: 'Öl, zum Braten'},
            {amount:'1', unit: "", ingredient: 'Paprikaschote(n), orange'},
            {amount:'2', unit: "EL", ingredient: 'Tomatenmark, (2-fach konzentriert)'},
            {amount:'1', unit: "gr. Dose/n", ingredient: 'Tomate(n), (ca. 800 g), stückig'},
            {amount:'1', unit: "Dose", ingredient: 'Kidneybohnen, (480g)'},
            {amount:'1', unit: "Dose", ingredient: 'Mais, (200g)'},
            {amount:'500', unit: "ml", ingredient: 'Brühe '},
            {amount:'', unit: "", ingredient: 'Cayennepfeffer'},
            {amount:'', unit: "", ingredient: 'Paprikapulver'},
            {amount:'', unit: "", ingredient: 'Chilipulver'},
            {amount:'', unit: "", ingredient: 'Salz und Pfeffer'},
            {amount:'', unit: "", ingredient: 'Zucker'},
            {amount:'', unit: "", ingredient: 'Tabasco'},
        ],
        [
            'Die Zwiebeln abziehen, in Würfel schneiden und in einem tiefen Topf oder Bräter im Öl goldgelb anbraten. Hackfleisch zufügen, gut anbraten und Farbe nehmen lassen. Dabei ab und zu umrühren und das Hackfleisch zerkleinern.',
            'Paprika putzen, in Würfel schneiden und zum Hackfleisch geben. Tomatenmark zufügen und etwas anrösten. Die Tomaten, den gepellten und zerkleinerten Knoblauch sowie Gewürze (Zucker, Salz, Pfeffer, Paprika, Tabasco, Chili oder Cayenne) zugeben. Allerdings lieber erst einmal etwas vorsichtiger würzen und gegebenenfalls nach der Kochzeit nachwürzen. Mit Brühe auffüllen und bei mittlerer Hitze 30 - 45 Minuten einkochen lassen, ist die Flüssigkeit verkocht, immer wieder Brühe angießen.',
            'Anrichten: Chili con Carne in einem tiefen Teller oder einer Schüssel servieren. Dazu passt ein knuspriges Baguette, Tortillas oder Nachos.',
            'Tipps: Wahlweise kann das Chili auch mit klein geschnittenem Fleisch und frischen Chilischoten zubereitet werden. Wer seinem "normalen" Chili einmal eine etwas andere Geschmacksrichtung geben möchte, verfeinert das obige Rezept mit einem Teelöffel Kreuzkümmel, einem Esslöffel dunklem Kakaopulver und einem doppelten Espresso! Guten Appetit! '
        ],
        'Chili con Carne',
        '4',
        '30 min',
        'https://img.chefkoch-cdn.de/rezepte/1578671265353584/bilder/1509269/crop-642x428/chili-con-carne.jpg'),
    new Recipe(
        3,
        'Fleisch',
        'Grüne Bohnen im Speckmantel',
        [
            {amount:'800', unit: 'g', ingredient:'Bohnen, grüne, frische'},
            {amount:'1', unit: 'Bund' , ingredient: 'Bohnenkraut '},
            {amount:'1', unit: '' , ingredient: 'Knoblauchzehe(n)'},
            {amount:'2', unit: 'TL', ingredient: 'Pfefferkörner'},
            {amount:'1', unit: 'EL', ingredient: 'Öl'},
            {amount:'8', unit: 'Scheibe/n', ingredient: 'Bacon'},
            {amount:'8',unit: 'EL' , ingredient: 'Butter'},
        ],
        [
            'Bohnen waschen und die Spitzen abschneiden.',
            'Bohnenkraut, Knoblauch, zerdrückte Pfefferkörner und Salz mit Öl kurz anrösten. 2 Liter Wasser zugießen, 10 Min. kochen, durchsieben. Diese Brühe aufkochen und die Bohnen in 3 Portionen nacheinander sprudelnd garen. Schnell in kaltem Wasser abkühlen, in einem Tuch abtrocknen.',
            'Zugedeckt im heißen Ofen bei 180 °C - 200 °C Ober-/Unterhitze erhitzen (ca. 5 Minuten), dabei einmal wenden.',
            'Die Bohnen sind eine schöne sommerliche Beilage zu festlichen Gerichten oder ein köstliches Hauptgericht mit ein paar Kartöffelchen.'
        ],
        'Grüne Bohnen im Speckmantel',
        '4',
        '30 min',
        'https://img.chefkoch-cdn.de/rezepte/563451154612271/bilder/1124631/crop-642x428/gruene-bohnen-im-speckmantel.jpg'),
    new Recipe(
        4,
        'Gemüse',
        'Gefüllte Zucchini aus dem Ofen',
        [
            {amount:'2', unit: '', ingredient:'Zucchini (ca. 300 - 340 g)'},
            {amount:'150', unit : 'g', ingredient: 'Frischkäse'},
            {amount:'100', unit : 'g', ingredient: 'Champignons '},
            {amount:'1', unit : 'kleine', ingredient: 'Zwiebel(n)'},
            {amount:'80', unit : 'g', ingredient: 'Cheddarkäse oder Gouda, gerieben (ca. 80 - 100 g)'},
            {amount:'', unit: '', ingredient: 'Salz und Pfeffer'},
        ],
        [
            'Als erstes werden die gewaschenen Zucchini der Länge nach halbiert und mit einem Löffel ausgehöhlt.',
            'Das ausgehöhlte Fruchtfleisch muss anschließend ganz fein gehackt werden. Außerdem kommen noch ganz fein gehackte Champignons, Zwiebeln und Knoblauch in die Füllung, sowie Frischkäse, Salz und Pfeffer. ',
            'Wenn sich alle Zutaten gut vermengt haben, kann die Füllung auch schon in den ausgehöhlten Zucchinihälften verteilt und glatt gestrichen werden. Am besten werden sie anschließend in eine leicht gefettete Auflaufform gelegt, mit geriebenem Cheddar oder Gouda bedeckt und danach im heißen Backofen bei 200 °C Ober-/Unterhitze ca. 20 - 25 Minuten gebacken.',
            'Als Beilage passen übrigens gekochter Reis oder frisches Baguette super gut.'
        ],
        'Gefüllte Zucchini aus dem Ofen',
        '4',
        '20 min',
        'https://img.chefkoch-cdn.de/rezepte/3089761461661487/bilder/1509483/crop-642x428/gefuellte-zucchini-aus-dem-ofen.jpg'),
    new Recipe(
        5,
        'Gemüse',
        'Chili con Carne',
        [
            {amount:'800', unit: "g", ingredient:'Rinderhackfleisch oder halb und halb'},
            {amount:'2', unit: "m.-große", ingredient: 'Zwiebel(n)'},
            {amount:'3', unit: "Zehe/n", ingredient: 'Knoblauch'},
            {amount:'2', unit: "EL", ingredient: 'Öl, zum Braten'},
            {amount:'1', unit: "", ingredient: 'Paprikaschote(n), orange'},
            {amount:'2', unit: "EL", ingredient: 'Tomatenmark, (2-fach konzentriert)'},
            {amount:'1', unit: "gr. Dose/n", ingredient: 'Tomate(n), (ca. 800 g), stückig'},
            {amount:'1', unit: "Dose", ingredient: 'Kidneybohnen, (480g)'},
            {amount:'1', unit: "Dose", ingredient: 'Mais, (200g)'},
            {amount:'500', unit: "ml", ingredient: 'Brühe '},
            {amount:'', unit: "", ingredient: 'Cayennepfeffer'},
            {amount:'', unit: "", ingredient: 'Paprikapulver'},
            {amount:'', unit: "", ingredient: 'Chilipulver'},
            {amount:'', unit: "", ingredient: 'Salz und Pfeffer'},
            {amount:'', unit: "", ingredient: 'Zucker'},
            {amount:'', unit: "", ingredient: 'Tabasco'},
        ],
        [
            'Die Zwiebeln abziehen, in Würfel schneiden und in einem tiefen Topf oder Bräter im Öl goldgelb anbraten. Hackfleisch zufügen, gut anbraten und Farbe nehmen lassen. Dabei ab und zu umrühren und das Hackfleisch zerkleinern.',
            'Paprika putzen, in Würfel schneiden und zum Hackfleisch geben. Tomatenmark zufügen und etwas anrösten. Die Tomaten, den gepellten und zerkleinerten Knoblauch sowie Gewürze (Zucker, Salz, Pfeffer, Paprika, Tabasco, Chili oder Cayenne) zugeben. Allerdings lieber erst einmal etwas vorsichtiger würzen und gegebenenfalls nach der Kochzeit nachwürzen. Mit Brühe auffüllen und bei mittlerer Hitze 30 - 45 Minuten einkochen lassen, ist die Flüssigkeit verkocht, immer wieder Brühe angießen.',
            'Anrichten: Chili con Carne in einem tiefen Teller oder einer Schüssel servieren. Dazu passt ein knuspriges Baguette, Tortillas oder Nachos.',
            'Tipps: Wahlweise kann das Chili auch mit klein geschnittenem Fleisch und frischen Chilischoten zubereitet werden. Wer seinem "normalen" Chili einmal eine etwas andere Geschmacksrichtung geben möchte, verfeinert das obige Rezept mit einem Teelöffel Kreuzkümmel, einem Esslöffel dunklem Kakaopulver und einem doppelten Espresso! Guten Appetit! '
        ],
        'Chili con Carne',
        '4',
        '30 min',
        'https://img.chefkoch-cdn.de/rezepte/1578671265353584/bilder/1509269/crop-642x428/chili-con-carne.jpg'),
    new Recipe(
        6,
        'Fleisch',
        'Grüne Bohnen im Speckmantel',
        [
            {amount:'800', unit: 'g', ingredient:'Bohnen, grüne, frische'},
            {amount:'1', unit: 'Bund' , ingredient: 'Bohnenkraut '},
            {amount:'1', unit: '' , ingredient: 'Knoblauchzehe(n)'},
            {amount:'2', unit: 'TL', ingredient: 'Pfefferkörner'},
            {amount:'1', unit: 'EL', ingredient: 'Öl'},
            {amount:'8', unit: 'Scheibe/n', ingredient: 'Bacon'},
            {amount:'8',unit: 'EL' , ingredient: 'Butter'},
        ],
        [
            'Bohnen waschen und die Spitzen abschneiden.',
            'Bohnenkraut, Knoblauch, zerdrückte Pfefferkörner und Salz mit Öl kurz anrösten. 2 Liter Wasser zugießen, 10 Min. kochen, durchsieben. Diese Brühe aufkochen und die Bohnen in 3 Portionen nacheinander sprudelnd garen. Schnell in kaltem Wasser abkühlen, in einem Tuch abtrocknen.',
            'Zugedeckt im heißen Ofen bei 180 °C - 200 °C Ober-/Unterhitze erhitzen (ca. 5 Minuten), dabei einmal wenden.',
            'Die Bohnen sind eine schöne sommerliche Beilage zu festlichen Gerichten oder ein köstliches Hauptgericht mit ein paar Kartöffelchen.'
        ],
        'Grüne Bohnen im Speckmantel',
        '4',
        '30 min',
        'https://img.chefkoch-cdn.de/rezepte/563451154612271/bilder/1124631/crop-642x428/gruene-bohnen-im-speckmantel.jpg'),
    new Recipe(
        7,
        'Gemüse',
        'Gefüllte Zucchini aus dem Ofen',
        [
            {amount:'2', unit: '', ingredient:'Zucchini (ca. 300 - 340 g)'},
            {amount:'150', unit : 'g', ingredient: 'Frischkäse'},
            {amount:'100', unit : 'g', ingredient: 'Champignons '},
            {amount:'1', unit : 'kleine', ingredient: 'Zwiebel(n)'},
            {amount:'80', unit : 'g', ingredient: 'Cheddarkäse oder Gouda, gerieben (ca. 80 - 100 g)'},
            {amount:'', unit: '', ingredient: 'Salz und Pfeffer'},
        ],
        [
            'Als erstes werden die gewaschenen Zucchini der Länge nach halbiert und mit einem Löffel ausgehöhlt.',
            'Das ausgehöhlte Fruchtfleisch muss anschließend ganz fein gehackt werden. Außerdem kommen noch ganz fein gehackte Champignons, Zwiebeln und Knoblauch in die Füllung, sowie Frischkäse, Salz und Pfeffer. ',
            'Wenn sich alle Zutaten gut vermengt haben, kann die Füllung auch schon in den ausgehöhlten Zucchinihälften verteilt und glatt gestrichen werden. Am besten werden sie anschließend in eine leicht gefettete Auflaufform gelegt, mit geriebenem Cheddar oder Gouda bedeckt und danach im heißen Backofen bei 200 °C Ober-/Unterhitze ca. 20 - 25 Minuten gebacken.',
            'Als Beilage passen übrigens gekochter Reis oder frisches Baguette super gut.'
        ],
        'Gefüllte Zucchini aus dem Ofen',
        '4',
        '20 min',
        'https://img.chefkoch-cdn.de/rezepte/3089761461661487/bilder/1509483/crop-642x428/gefuellte-zucchini-aus-dem-ofen.jpg'),
    new Recipe(
        8,
        'Gemüse',
        'Chili con Carne',
        [
            {amount:'800', unit: "g", ingredient:'Rinderhackfleisch oder halb und halb'},
            {amount:'2', unit: "m.-große", ingredient: 'Zwiebel(n)'},
            {amount:'3', unit: "Zehe/n", ingredient: 'Knoblauch'},
            {amount:'2', unit: "EL", ingredient: 'Öl, zum Braten'},
            {amount:'1', unit: "", ingredient: 'Paprikaschote(n), orange'},
            {amount:'2', unit: "EL", ingredient: 'Tomatenmark, (2-fach konzentriert)'},
            {amount:'1', unit: "gr. Dose/n", ingredient: 'Tomate(n), (ca. 800 g), stückig'},
            {amount:'1', unit: "Dose", ingredient: 'Kidneybohnen, (480g)'},
            {amount:'1', unit: "Dose", ingredient: 'Mais, (200g)'},
            {amount:'500', unit: "ml", ingredient: 'Brühe '},
            {amount:'', unit: "", ingredient: 'Cayennepfeffer'},
            {amount:'', unit: "", ingredient: 'Paprikapulver'},
            {amount:'', unit: "", ingredient: 'Chilipulver'},
            {amount:'', unit: "", ingredient: 'Salz und Pfeffer'},
            {amount:'', unit: "", ingredient: 'Zucker'},
            {amount:'', unit: "", ingredient: 'Tabasco'},
        ],
        [
            'Die Zwiebeln abziehen, in Würfel schneiden und in einem tiefen Topf oder Bräter im Öl goldgelb anbraten. Hackfleisch zufügen, gut anbraten und Farbe nehmen lassen. Dabei ab und zu umrühren und das Hackfleisch zerkleinern.',
            'Paprika putzen, in Würfel schneiden und zum Hackfleisch geben. Tomatenmark zufügen und etwas anrösten. Die Tomaten, den gepellten und zerkleinerten Knoblauch sowie Gewürze (Zucker, Salz, Pfeffer, Paprika, Tabasco, Chili oder Cayenne) zugeben. Allerdings lieber erst einmal etwas vorsichtiger würzen und gegebenenfalls nach der Kochzeit nachwürzen. Mit Brühe auffüllen und bei mittlerer Hitze 30 - 45 Minuten einkochen lassen, ist die Flüssigkeit verkocht, immer wieder Brühe angießen.',
            'Anrichten: Chili con Carne in einem tiefen Teller oder einer Schüssel servieren. Dazu passt ein knuspriges Baguette, Tortillas oder Nachos.',
            'Tipps: Wahlweise kann das Chili auch mit klein geschnittenem Fleisch und frischen Chilischoten zubereitet werden. Wer seinem "normalen" Chili einmal eine etwas andere Geschmacksrichtung geben möchte, verfeinert das obige Rezept mit einem Teelöffel Kreuzkümmel, einem Esslöffel dunklem Kakaopulver und einem doppelten Espresso! Guten Appetit! '
        ],
        'Chili con Carne',
        '4',
        '30 min',
        'https://img.chefkoch-cdn.de/rezepte/1578671265353584/bilder/1509269/crop-642x428/chili-con-carne.jpg'),
    new Recipe(
        9,
        'Fleisch',
        'Grüne Bohnen im Speckmantel',
        [
            {amount:'800', unit: 'g', ingredient:'Bohnen, grüne, frische'},
            {amount:'1', unit: 'Bund' , ingredient: 'Bohnenkraut '},
            {amount:'1', unit: '' , ingredient: 'Knoblauchzehe(n)'},
            {amount:'2', unit: 'TL', ingredient: 'Pfefferkörner'},
            {amount:'1', unit: 'EL', ingredient: 'Öl'},
            {amount:'8', unit: 'Scheibe/n', ingredient: 'Bacon'},
            {amount:'8',unit: 'EL' , ingredient: 'Butter'},
        ],
        [
            'Bohnen waschen und die Spitzen abschneiden.',
            'Bohnenkraut, Knoblauch, zerdrückte Pfefferkörner und Salz mit Öl kurz anrösten. 2 Liter Wasser zugießen, 10 Min. kochen, durchsieben. Diese Brühe aufkochen und die Bohnen in 3 Portionen nacheinander sprudelnd garen. Schnell in kaltem Wasser abkühlen, in einem Tuch abtrocknen.',
            'Zugedeckt im heißen Ofen bei 180 °C - 200 °C Ober-/Unterhitze erhitzen (ca. 5 Minuten), dabei einmal wenden.',
            'Die Bohnen sind eine schöne sommerliche Beilage zu festlichen Gerichten oder ein köstliches Hauptgericht mit ein paar Kartöffelchen.'
        ],
        'Grüne Bohnen im Speckmantel',
        '4',
        '30 min',
        'https://img.chefkoch-cdn.de/rezepte/563451154612271/bilder/1124631/crop-642x428/gruene-bohnen-im-speckmantel.jpg'),
    new Recipe(
        10,
        'Gemüse',
        'Gefüllte Zucchini aus dem Ofen',
        [
            {amount:'2', unit: '', ingredient:'Zucchini (ca. 300 - 340 g)'},
            {amount:'150', unit : 'g', ingredient: 'Frischkäse'},
            {amount:'100', unit : 'g', ingredient: 'Champignons '},
            {amount:'1', unit : 'kleine', ingredient: 'Zwiebel(n)'},
            {amount:'80', unit : 'g', ingredient: 'Cheddarkäse oder Gouda, gerieben (ca. 80 - 100 g)'},
            {amount:'', unit: '', ingredient: 'Salz und Pfeffer'},
        ],
        [
            'Als erstes werden die gewaschenen Zucchini der Länge nach halbiert und mit einem Löffel ausgehöhlt.',
            'Das ausgehöhlte Fruchtfleisch muss anschließend ganz fein gehackt werden. Außerdem kommen noch ganz fein gehackte Champignons, Zwiebeln und Knoblauch in die Füllung, sowie Frischkäse, Salz und Pfeffer. ',
            'Wenn sich alle Zutaten gut vermengt haben, kann die Füllung auch schon in den ausgehöhlten Zucchinihälften verteilt und glatt gestrichen werden. Am besten werden sie anschließend in eine leicht gefettete Auflaufform gelegt, mit geriebenem Cheddar oder Gouda bedeckt und danach im heißen Backofen bei 200 °C Ober-/Unterhitze ca. 20 - 25 Minuten gebacken.',
            'Als Beilage passen übrigens gekochter Reis oder frisches Baguette super gut.'
        ],
        'Gefüllte Zucchini aus dem Ofen',
        '4',
        '20 min',
        'https://img.chefkoch-cdn.de/rezepte/3089761461661487/bilder/1509483/crop-642x428/gefuellte-zucchini-aus-dem-ofen.jpg'),
    new Recipe(
        11,
        'Gemüse',
        'Chili con Carne',
        [
            {amount:'800', unit: "g", ingredient:'Rinderhackfleisch oder halb und halb'},
            {amount:'2', unit: "m.-große", ingredient: 'Zwiebel(n)'},
            {amount:'3', unit: "Zehe/n", ingredient: 'Knoblauch'},
            {amount:'2', unit: "EL", ingredient: 'Öl, zum Braten'},
            {amount:'1', unit: "", ingredient: 'Paprikaschote(n), orange'},
            {amount:'2', unit: "EL", ingredient: 'Tomatenmark, (2-fach konzentriert)'},
            {amount:'1', unit: "gr. Dose/n", ingredient: 'Tomate(n), (ca. 800 g), stückig'},
            {amount:'1', unit: "Dose", ingredient: 'Kidneybohnen, (480g)'},
            {amount:'1', unit: "Dose", ingredient: 'Mais, (200g)'},
            {amount:'500', unit: "ml", ingredient: 'Brühe '},
            {amount:'', unit: "", ingredient: 'Cayennepfeffer'},
            {amount:'', unit: "", ingredient: 'Paprikapulver'},
            {amount:'', unit: "", ingredient: 'Chilipulver'},
            {amount:'', unit: "", ingredient: 'Salz und Pfeffer'},
            {amount:'', unit: "", ingredient: 'Zucker'},
            {amount:'', unit: "", ingredient: 'Tabasco'},
        ],
        [
            'Die Zwiebeln abziehen, in Würfel schneiden und in einem tiefen Topf oder Bräter im Öl goldgelb anbraten. Hackfleisch zufügen, gut anbraten und Farbe nehmen lassen. Dabei ab und zu umrühren und das Hackfleisch zerkleinern.',
            'Paprika putzen, in Würfel schneiden und zum Hackfleisch geben. Tomatenmark zufügen und etwas anrösten. Die Tomaten, den gepellten und zerkleinerten Knoblauch sowie Gewürze (Zucker, Salz, Pfeffer, Paprika, Tabasco, Chili oder Cayenne) zugeben. Allerdings lieber erst einmal etwas vorsichtiger würzen und gegebenenfalls nach der Kochzeit nachwürzen. Mit Brühe auffüllen und bei mittlerer Hitze 30 - 45 Minuten einkochen lassen, ist die Flüssigkeit verkocht, immer wieder Brühe angießen.',
            'Anrichten: Chili con Carne in einem tiefen Teller oder einer Schüssel servieren. Dazu passt ein knuspriges Baguette, Tortillas oder Nachos.',
            'Tipps: Wahlweise kann das Chili auch mit klein geschnittenem Fleisch und frischen Chilischoten zubereitet werden. Wer seinem "normalen" Chili einmal eine etwas andere Geschmacksrichtung geben möchte, verfeinert das obige Rezept mit einem Teelöffel Kreuzkümmel, einem Esslöffel dunklem Kakaopulver und einem doppelten Espresso! Guten Appetit! '
        ],
        'Chili con Carne',
        '4',
        '30 min',
        'https://img.chefkoch-cdn.de/rezepte/1578671265353584/bilder/1509269/crop-642x428/chili-con-carne.jpg')
    ];